# action.yml
name: 'Rust build .deb with cargo-deb ARMv7'
description: 'Builds a debian package using cargo deb for Rust packages, statically linked (musl), targeting ARMv7'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  cmd:
    description: 'build command'
    required: true
    default: 'cargo deb --target=armv7-unknown-linux-musleabihf'
runs:
  using: 'docker'
  image: 'docker://asthowen/cargo-deb-armv7:latest'
  args:
    - ${{ inputs.cmd }}